// AUTO-GENERATED from the XYRO mascot artwork (WhatsApp Image 2026-09-01).
// Braille trace (2×4 dots per cell). Mask: w = outline, b = glowing eyes/mouth,
// x = forehead X + orbit ring. Do not edit by hand — regenerate instead.

export interface MascotArt { cols: number; rows: number; open: string[]; blink: string[]; mask: string[]; blinkMask: string[] }

export const MASCOT_ART: MascotArt[] = [
  { cols: 52, rows: 21,
    open: [
      "               ⢀⣀⠤⠒⠊⠉⠙⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠑⠒⠤⣀⡀               ",
      "              ⠚⠁⠁      ⡤⠤⠤⡄        ⠈⠉⠒⠄             ",
      "           ⠔⠋          ⠹⡀ ⠱⡀   ⣀⣀⣀     ⠙⠢           ",
      "         ⡰⠛             ⠹⡀ ⠘⡄⠾⣭⠗⢀⡬⠃      ⠛⢆         ",
      "        ⠞⠁              ⡰⠁⢀⣠⠽⢋⡥⠚⠁         ⠈⠣        ",
      "       ⠞             ⣀⢀⣞⠥⢚⣫⡴⠚⠑⠄             ⠳       ",
      "      ⡸⠁            ⠘⠯⠭⠴⠖⠉ ⢳  ⠹⡀            ⠈⢇      ",
      "     ⢐⠃  ⢀⠤⠤⠤⠤⢤⣀⡀           ⠓⠖⠲⠓   ⢀⣀⠤⠤⠤⠤⢤⡀  ⠘⡂     ",
      "    ⣠⢾ ⢀⠜⠁⢀⣀⣠⣠⣀⣈⣉⠛⠒⠦⣤⣀⣀      ⣀⣠⡤⠴⠒⠛⣉⣀⣄⣄⣤⣀⡀⠈⢢⡀ ⡧⣄    ",
      " ⣠⡴⠋⢱⣼⢀⡞ ⡔⠉     ⠉⠙⠒⠤⠤⢀⣉⠉⠛⠛⠛⠛⠉⣁⣠⠤⠤⠒⠋⠉     ⠉⢦ ⢳⡀⣧⣏⠙⢦⣄ ",
      "⢠⠇⡇ ⢸⣿⢨ ⡬⠁            ⠈⠉⠉⠉⠋⠙⠉⠁            ⠈⢥ ⡅⢹⣯ ⢸⠸⡄",
      "⡌ ⡇ ⢸⣯⢨ ⡇     ⣀⣤⣤⣄⡀              ⢀⣀⣤⣤⡀     ⢸ ⡅⢸⣧ ⢸ ⢡",
      "⡇ ⡇ ⢸⣯⢸ ⡇    ⣰⡿⠋⠉⠻⣷⡀            ⢀⣾⠟⠉⠙⢿⣆    ⢸ ⡇⢸⣧ ⢸ ⢸",
      "⡇ ⡇ ⢸⣧⢸ ⡇    ⣿⡀   ⣺⡇            ⢸⣗   ⢘⣿    ⢸ ⡇⢸⣧ ⢸ ⢸",
      "⢰⡀⡇ ⢸⣷⢰⡀⣇    ⠙⠁   ⠉⠁            ⠈⠉   ⠈⠉    ⣸⢀⡆⢸⣧ ⢸⢀⡆",
      " ⠒⢣⣄⣸⣷ ⢦⠐⡄            ⣀⡀    ⢀⣄            ⢠⠂⡴ ⣾⣷⣠⡜⠒ ",
      "   ⠈⠙⢸ ⠘⡄⠘⢄           ⠈⠻⠶⠶⠶⠾⠛⠁           ⡠⠃⢠⠃ ⡇⠋⠁   ",
      "     ⠈⢇ ⠘⢆ ⠑⠲⠤⣀⣀                    ⣀⣀⠤⠖⠊ ⡰⠃ ⡸⠁     ",
      "      ⠈⠙⢦⡈⠉⠢⢤⣀⡀⠈⠉⠓⠒⠖⠦⢤⣤⣤⣤⣤⣤⣤⣤⣤⡤⠶⠶⠒⠚⠉⠁⢀⣀⡤⠖⠉⢀⡴⠋⠁      ",
      "         ⠈⠛⠢⠤⣀⡉⠙⠓⠒⠢⠤⣤⣄⣀⣀⣀⣀⣀⣀⣀⣀⣠⡤⠤⠖⠒⠚⠋⢉⣀⠤⠔⠛⠁         ",
      "              ⠉⠙⠒⠒⠤⠤⠤⠤⣄⣀⣀⣀⣀⣀⣀⡠⠤⠤⠤⠤⠒⠚⠊⠉              ",
    ],
    blink: [
      "               ⢀⣀⠤⠒⠊⠉⠙⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠑⠒⠤⣀⡀               ",
      "              ⠚⠁⠁      ⡤⠤⠤⡄        ⠈⠉⠒⠄             ",
      "           ⠔⠋          ⠹⡀ ⠱⡀   ⣀⣀⣀     ⠙⠢           ",
      "         ⡰⠛             ⠹⡀ ⠘⡄⠾⣭⠗⢀⡬⠃      ⠛⢆         ",
      "        ⠞⠁              ⡰⠁⢀⣠⠽⢋⡥⠚⠁         ⠈⠣        ",
      "       ⠞             ⣀⢀⣞⠥⢚⣫⡴⠚⠑⠄             ⠳       ",
      "      ⡸⠁            ⠘⠯⠭⠴⠖⠉ ⢳  ⠹⡀            ⠈⢇      ",
      "     ⢐⠃  ⢀⠤⠤⠤⠤⢤⣀⡀           ⠓⠖⠲⠓   ⢀⣀⠤⠤⠤⠤⢤⡀  ⠘⡂     ",
      "    ⣠⢾ ⢀⠜⠁⢀⣀⣠⣠⣀⣈⣉⠛⠒⠦⣤⣀⣀      ⣀⣠⡤⠴⠒⠛⣉⣀⣄⣄⣤⣀⡀⠈⢢⡀ ⡧⣄    ",
      " ⣠⡴⠋⢱⣼⢀⡞ ⡔⠉     ⠉⠙⠒⠤⠤⢀⣉⠉⠛⠛⠛⠛⠉⣁⣠⠤⠤⠒⠋⠉     ⠉⢦ ⢳⡀⣧⣏⠙⢦⣄ ",
      "⢠⠇⡇ ⢸⣿⢨ ⡬⠁            ⠈⠉⠉⠉⠋⠙⠉⠁            ⠈⢥ ⡅⢹⣯ ⢸⠸⡄",
      "⡌ ⡇ ⢸⣯⢨ ⡇                                  ⢸ ⡅⢸⣧ ⢸ ⢡",
      "⡇ ⡇ ⢸⣯⢸ ⡇                                  ⢸ ⡇⢸⣧ ⢸ ⢸",
      "⡇ ⡇ ⢸⣧⢸ ⡇    ⠶⠶⠶⠶⠶⠶⠦            ⠰⠶⠶⠶⠶⠶⠶⠄   ⢸ ⡇⢸⣧ ⢸ ⢸",
      "⢰⡀⡇ ⢸⣷⢰⡀⣇                                  ⣸⢀⡆⢸⣧ ⢸⢀⡆",
      " ⠒⢣⣄⣸⣷ ⢦⠐⡄            ⣀⡀    ⢀⣄            ⢠⠂⡴ ⣾⣷⣠⡜⠒ ",
      "   ⠈⠙⢸ ⠘⡄⠘⢄           ⠈⠻⠶⠶⠶⠾⠛⠁           ⡠⠃⢠⠃ ⡇⠋⠁   ",
      "     ⠈⢇ ⠘⢆ ⠑⠲⠤⣀⣀                    ⣀⣀⠤⠖⠊ ⡰⠃ ⡸⠁     ",
      "      ⠈⠙⢦⡈⠉⠢⢤⣀⡀⠈⠉⠓⠒⠖⠦⢤⣤⣤⣤⣤⣤⣤⣤⣤⡤⠶⠶⠒⠚⠉⠁⢀⣀⡤⠖⠉⢀⡴⠋⠁      ",
      "         ⠈⠛⠢⠤⣀⡉⠙⠓⠒⠢⠤⣤⣄⣀⣀⣀⣀⣀⣀⣀⣀⣠⡤⠤⠖⠒⠚⠋⢉⣀⠤⠔⠛⠁         ",
      "              ⠉⠙⠒⠒⠤⠤⠤⠤⣄⣀⣀⣀⣀⣀⣀⡠⠤⠤⠤⠤⠒⠚⠊⠉              ",
    ],
    mask: [
      "               wwwwwwwwwwwwwwwwwwwwww               ",
      "              www      xxxx        wwww             ",
      "           ww          xx xx   xxx     ww           ",
      "         ww             xx xxxxxxxx      ww         ",
      "        ww              xxxxxxxxx         ww        ",
      "       w             xxxxxxxxxx             w       ",
      "      ww            xxxxxx x  xx            ww      ",
      "     ww  wwwwwwww           xxxx   wwwwwwww  ww     ",
      "    ww wwwwwwwwwwwwwwww      wwwwwwwwwwwwwwww ww    ",
      " wwwwwww ww     wwwwwwwwwwwwwwwwwwww     ww wwwwwww ",
      "www www ww            wwwwwwww            ww www www",
      "w w www w     bbbbb              bbbbb     w www w w",
      "w w www w    bbbbbbb            bbbbbbb    w www w w",
      "w w www w    bb   bb            bb   bb    w www w w",
      "www wwwww    bb   bb            bb   bb    wwwww www",
      " wwwww www            bb    bb            www wwwww ",
      "   www wwww           bbbbbbbb           wwww www   ",
      "     ww ww wwwww                    wwwww ww ww     ",
      "      wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww      ",
      "         wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww         ",
      "              wwwwwwwwwwwwwwwwwwwwwwww              ",
    ],
    blinkMask: [
      "               wwwwwwwwwwwwwwwwwwwwww               ",
      "              www      xxxx        wwww             ",
      "           ww          xx xx   xxx     ww           ",
      "         ww             xx xxxxxxxx      ww         ",
      "        ww              xxxxxxxxx         ww        ",
      "       w             xxxxxxxxxx             w       ",
      "      ww            xxxxxx x  xx            ww      ",
      "     ww  wwwwwwww           xxxx   wwwwwwww  ww     ",
      "    ww wwwwwwwwwwwwwwww      wwwwwwwwwwwwwwww ww    ",
      " wwwwwww ww     wwwwwwwwwwwwwwwwwwww     ww wwwwwww ",
      "www www ww            wwwwwwww            ww www www",
      "w w www w                                  w www w w",
      "w w www w                                  w www w w",
      "w w www w    bbbbbbb            bbbbbbbb   w www w w",
      "www wwwww                                  wwwww www",
      " wwwww www            bb    bb            www wwwww ",
      "   www wwww           bbbbbbbb           wwww www   ",
      "     ww ww wwwww                    wwwww ww ww     ",
      "      wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww      ",
      "         wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww         ",
      "              wwwwwwwwwwwwwwwwwwwwwwww              ",
    ],
  },
  { cols: 44, rows: 18,
    open: [
      "             ⣠⠤⠒⠊⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠑⠒⠤⣄             ",
      "          ⣠ ⠉      ⢠⠒⠒⡆        ⠉ ⣄          ",
      "        ⣠⡎          ⢣ ⠘⢆⢀⡠⢴⠒⢦     ⢡⣄        ",
      "       ⡰⠁           ⢀⡣ ⢈⡮⢟⣩⠖⠉      ⠈⢆       ",
      "      ⡔            ⢠⣂⠤⢒⡭⠖⠍           ⢢      ",
      "     ⡸           ⠸⠭⠭⠖⠚⠁⢇ ⠘⡄           ⢇     ",
      "    ⢀⠃ ⢀⡤⠤⠤⠤⢤⣀⡀        ⠈⠒⠒⠚  ⢀⣀⡠⠤⠤⠤⢤⡀ ⠘⡀    ",
      "  ⢀⣤⢺ ⣰⠋⢀⠤⠤⠤⠦⠤⣍⡉⠒⠦⠤⣄⣀⣀⣀⣀⣠⠤⠖⠒⢉⣩⠤⠤⠤⠴⠤⡀⠙⣆ ⡗⣤⡀  ",
      " ⣶⠉⢰⢸⠰⠃⠰⠁      ⠉⠉⠒⠲⠤⣤⣤⣤⣤⠤⠒⠒⠉⠉      ⠈⠆⠘⠆⡇⡆⠙⣶ ",
      "⡘⢸ ⢸⣻⢸ ⡃                            ⢘ ⡇⣟⡇ ⡇⢃",
      "⡇⢸ ⢸⣻⢸ ⡇   ⢠⡾⠛⠻⣦⡀           ⣴⠟⠛⢷⣄   ⢸ ⡇⣟⡇ ⡇⢸",
      "⡇⢸ ⢸⣽⢨ ⡇   ⣿   ⢸⡇          ⢸⡇   ⣿   ⢸ ⡅⣯⡇ ⡇⢸",
      "⠲⢸ ⢸⢾⠰ ⡆   ⠉   ⠈⠁          ⠈⠁   ⠉   ⢰ ⠆⡷⡇ ⡇⠖",
      " ⠉⠶⣼⢸ ⣇⠱⡀         ⠠⣤⣀  ⣀⣤          ⢀⠆⣸ ⡇⣧⠔⠉ ",
      "    ⠘⡄⠘⢆⠑⢦⣀        ⠈⠉⠉⠛⠋⠁        ⣀⡔⠊⡐⠃⢠⠃    ",
      "     ⠐⢄⡈⠢⣄⡈⠉⠒⠲⠤⢄⣀⣀        ⣀⣀⡠⠤⠒⠒⠉⢁⣠⠖⢁⡠⠂     ",
      "       ⠈⠲⠤⣈⠙⠒⠶⠤⠤⣀⣀⡉⠉⠉⠉⠉⠉⠉⣉⣀⣀⠤⠤⠖⠒⠋⣁⠤⠖⠁       ",
      "           ⠉⠑⠒⠲⠤⠤⠤⢬⣉⣉⣉⣉⣉⣉⠥⠤⠤⠤⠖⠒⠊⠉           ",
    ],
    blink: [
      "             ⣠⠤⠒⠊⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠑⠒⠤⣄             ",
      "          ⣠ ⠉      ⢠⠒⠒⡆        ⠉ ⣄          ",
      "        ⣠⡎          ⢣ ⠘⢆⢀⡠⢴⠒⢦     ⢡⣄        ",
      "       ⡰⠁           ⢀⡣ ⢈⡮⢟⣩⠖⠉      ⠈⢆       ",
      "      ⡔            ⢠⣂⠤⢒⡭⠖⠍           ⢢      ",
      "     ⡸           ⠸⠭⠭⠖⠚⠁⢇ ⠘⡄           ⢇     ",
      "    ⢀⠃ ⢀⡤⠤⠤⠤⢤⣀⡀        ⠈⠒⠒⠚  ⢀⣀⡠⠤⠤⠤⢤⡀ ⠘⡀    ",
      "  ⢀⣤⢺ ⣰⠋⢀⠤⠤⠤⠦⠤⣍⡉⠒⠦⠤⣄⣀⣀⣀⣀⣠⠤⠖⠒⢉⣩⠤⠤⠤⠴⠤⡀⠙⣆ ⡗⣤⡀  ",
      " ⣶⠉⢰⢸⠰⠃⠰⠁      ⠉⠉⠒⠲⠤⣤⣤⣤⣤⠤⠒⠒⠉⠉      ⠈⠆⠘⠆⡇⡆⠙⣶ ",
      "⡘⢸ ⢸⣻⢸ ⡃                            ⢘ ⡇⣟⡇ ⡇⢃",
      "⡇⢸ ⢸⣻⢸ ⡇                            ⢸ ⡇⣟⡇ ⡇⢸",
      "⡇⢸ ⢸⣽⢨ ⡇   ⠤⠤⠤⠤⠤⠤          ⠠⠤⠤⠤⠤⠤   ⢸ ⡅⣯⡇ ⡇⢸",
      "⠲⢸ ⢸⢾⠰ ⡆                            ⢰ ⠆⡷⡇ ⡇⠖",
      " ⠉⠶⣼⢸ ⣇⠱⡀         ⠠⣤⣀  ⣀⣤          ⢀⠆⣸ ⡇⣧⠔⠉ ",
      "    ⠘⡄⠘⢆⠑⢦⣀        ⠈⠉⠉⠛⠋⠁        ⣀⡔⠊⡐⠃⢠⠃    ",
      "     ⠐⢄⡈⠢⣄⡈⠉⠒⠲⠤⢄⣀⣀        ⣀⣀⡠⠤⠒⠒⠉⢁⣠⠖⢁⡠⠂     ",
      "       ⠈⠲⠤⣈⠙⠒⠶⠤⠤⣀⣀⡉⠉⠉⠉⠉⠉⠉⣉⣀⣀⠤⠤⠖⠒⠋⣁⠤⠖⠁       ",
      "           ⠉⠑⠒⠲⠤⠤⠤⢬⣉⣉⣉⣉⣉⣉⠥⠤⠤⠤⠖⠒⠊⠉           ",
    ],
    mask: [
      "             wwwwwwwwwwwwwwwwww             ",
      "          w w      xxxx        w w          ",
      "        ww          x xxxxxxx     ww        ",
      "       ww           xx xxxxxx      ww       ",
      "      w            xxxxxxx           w      ",
      "     w           xxxxxxx xx           w     ",
      "    ww wwwwwwww        wwww  wwwwwwww ww    ",
      "  www wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww www  ",
      " wwwwwwww      wwwwwwwwwwwwww      wwwwwwww ",
      "ww www w                            w www ww",
      "ww www w   bbbbbb           bbbbb   w www ww",
      "ww www w   b   bb          bb   b   w www ww",
      "ww www w   w   ww          ww   b   w www ww",
      " wwww www         bbb  bb          www wwww ",
      "    wwwwwww        bbbbbb        wwwwwww    ",
      "     wwwwwwwwwwwww        wwwwwwwwwwwww     ",
      "       wwwwwwwwwwwwwwwwwwwwwwwwwwwwww       ",
      "           wwwwwwwwwwwwwwwwwwwwww           ",
    ],
    blinkMask: [
      "             wwwwwwwwwwwwwwwwww             ",
      "          w w      xxxx        w w          ",
      "        ww          x xxxxxxx     ww        ",
      "       ww           xx xxxxxx      ww       ",
      "      w            xxxxxxx           w      ",
      "     w           xxxxxxx xx           w     ",
      "    ww wwwwwwww        wwww  wwwwwwww ww    ",
      "  www wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww www  ",
      " wwwwwwww      wwwwwwwwwwwwww      wwwwwwww ",
      "ww www w                            w www ww",
      "ww www w                            w www ww",
      "ww www w   bbbbbb          bbbbbb   w www ww",
      "ww www w                            w www ww",
      " wwww www         bbb  bb          www wwww ",
      "    wwwwwww        bbbbbb        wwwwwww    ",
      "     wwwwwwwwwwwww        wwwwwwwwwwwww     ",
      "       wwwwwwwwwwwwwwwwwwwwwwwwwwwwww       ",
      "           wwwwwwwwwwwwwwwwwwwwww           ",
    ],
  },
  { cols: 36, rows: 14,
    open: [
      "          ⣀⠔⠒⠊⠉⠉⠉⠉⠉⠉⠉⠉⠑⠒⠢⣀          ",
      "       ⠠⠔⠁      ⢏⠉⢇  ⢀⣀⡀   ⠢⡄       ",
      "      ⡔⠁        ⠈⠃ ⢣⡺⢗⡤⠚    ⠈⢢      ",
      "     ⠎         ⣀⣔⠥⣒⠭⠪⠁        ⠱     ",
      "    ⡜         ⠘⠚⠚⠉⠈⢆⣀⣣         ⢣    ",
      "   ⣰ ⢠⠚⢉⣉⣉⣑⡒⠤⠤⣀⣀    ⣀⣀⠤⠤⢒⣊⣉⣉⡉⠓⡄ ⣆   ",
      "⢠⣶⠉⣿⢠⠃⡜⠁   ⠈⠙⠒⠂⠬⣉⣉⣉⣉⠥⠐⠒⠋⠁   ⠈⠢⠘⡄⣿⠙⣦⡄",
      "⡊⡃ ⣿⢸⢸    ⣀⣀⡀          ⢀⣀⣀    ⡇⡇⣿ ⣛⢑",
      "⡇⡇ ⣿⢸⢸   ⣼⠋⠉⢻⡆        ⢰⡟⠉⠙⣷   ⡇⡇⣿ ⢶⢸",
      "⢇⡅ ⣿⢸⢸   ⠛  ⠘⠃        ⠘⠃  ⠛   ⡇⡇⣿ ⣨⡨",
      " ⠓⠤⣿ ⡆⢂        ⠠⣄⡀⢀⣠⠄        ⡐⢰ ⣿⠤⠊ ",
      "   ⠈⢆⠈⢄⠑⠤⢀⣀     ⠈⠉⠉⠁     ⣀⡠⠤⠊⡰⠁⡰⠁   ",
      "     ⠑⠄⣑⠲⠤⢈⣉⡑⠒⠒⠠⠤⠤⠤⠤⠄⠒⠒⢈⣉⡠⠤⠒⣊⠠⠊⠁    ",
      "        ⠉⠐⠂⠤⠤⢉⣉⣑⣒⣒⣒⣒⣊⣉⡉⠤⠤⠒⠊⠉        ",
    ],
    blink: [
      "          ⣀⠔⠒⠊⠉⠉⠉⠉⠉⠉⠉⠉⠑⠒⠢⣀          ",
      "       ⠠⠔⠁      ⢏⠉⢇  ⢀⣀⡀   ⠢⡄       ",
      "      ⡔⠁        ⠈⠃ ⢣⡺⢗⡤⠚    ⠈⢢      ",
      "     ⠎         ⣀⣔⠥⣒⠭⠪⠁        ⠱     ",
      "    ⡜         ⠘⠚⠚⠉⠈⢆⣀⣣         ⢣    ",
      "   ⣰ ⢠⠚⢉⣉⣉⣑⡒⠤⠤⣀⣀    ⣀⣀⠤⠤⢒⣊⣉⣉⡉⠓⡄ ⣆   ",
      "⢠⣶⠉⣿⢠⠃⡜⠁   ⠈⠙⠒⠂⠬⣉⣉⣉⣉⠥⠐⠒⠋⠁   ⠈⠢⠘⡄⣿⠙⣦⡄",
      "⡊⡃ ⣿⢸⢸                        ⡇⡇⣿ ⣛⢑",
      "⡇⡇ ⣿⢸⢸                        ⡇⡇⣿ ⢶⢸",
      "⢇⡅ ⣿⢸⢸   ⠉⠉⠉⠉⠁        ⠈⠉⠉⠉⠉   ⡇⡇⣿ ⣨⡨",
      " ⠓⠤⣿ ⡆⢂        ⠠⣄⡀⢀⣠⠄        ⡐⢰ ⣿⠤⠊ ",
      "   ⠈⢆⠈⢄⠑⠤⢀⣀     ⠈⠉⠉⠁     ⣀⡠⠤⠊⡰⠁⡰⠁   ",
      "     ⠑⠄⣑⠲⠤⢈⣉⡑⠒⠒⠠⠤⠤⠤⠤⠄⠒⠒⢈⣉⡠⠤⠒⣊⠠⠊⠁    ",
      "        ⠉⠐⠂⠤⠤⢉⣉⣑⣒⣒⣒⣒⣊⣉⡉⠤⠤⠒⠊⠉        ",
    ],
    mask: [
      "          wwwwwwwwwwwwwwww          ",
      "       www      xxx  xxx   ww       ",
      "      ww        xx xxxxx    ww      ",
      "     w         xxxxxxx        w     ",
      "    w         xxxxxxxx         w    ",
      "   w wwwwwwwwwww    wwwwwwwwwww w   ",
      "wwwwwwww   wwwwwwwwwwwwww   wwwwwwww",
      "ww www    bbw          bbb    www ww",
      "ww www   bbbbb        bbbbb   www ww",
      "ww www   b  bb        bb  b   www ww",
      " www ww        bbbbbb        ww www ",
      "   wwwwwwww     bbbb     wwwwwwww   ",
      "     wwwwwwwwwwwwwwwwwwwwwwwwwww    ",
      "        wwwwwwwwwwwwwwwwwwww        ",
    ],
    blinkMask: [
      "          wwwwwwwwwwwwwwww          ",
      "       www      xxx  xxx   ww       ",
      "      ww        xx xxxxx    ww      ",
      "     w         xxxxxxx        w     ",
      "    w         xxxxxxxx         w    ",
      "   w wwwwwwwwwww    wwwwwwwwwww w   ",
      "wwwwwwww   wwwwwwwwwwwwww   wwwwwwww",
      "ww www                        www ww",
      "ww www                        www ww",
      "ww www   bbbbb        bbbbb   www ww",
      " www ww        bbbbbb        ww www ",
      "   wwwwwwww     bbbb     wwwwwwww   ",
      "     wwwwwwwwwwwwwwwwwwwwwwwwwww    ",
      "        wwwwwwwwwwwwwwwwwwww        ",
    ],
  },
  { cols: 26, rows: 10,
    open: [
      "       ⠄⠒⠉⠉⢈⣉⡉⠉⠉⠉⠒⠠       ",
      "    ⢠⠌     ⠈⠆⠱⣠⡰⡒  ⠈⠠⡄    ",
      "   ⠠⠁     ⢀⣠⢥⣲⠙⡉     ⠈⠄   ",
      "  ⢀⠂⢀⠤⠤⢄⣀ ⠈⠉⠁ ⠢⠕ ⣀⠠⠤⠤⡀⠐⡀  ",
      "⢠⡔⣾⠰⠡⠊⠉⠁⠒⠪⠭⢒⣒⣒⡒⠭⠕⠒⠈⠉⠑⠌⠆⣿⢢⡄",
      "⡅⡇⣿⠅⡇ ⢀⣤⢤⡀      ⢀⡤⣤⡀ ⢸⠨⣿⢸⢨",
      "⡇⡇⣿⡇⡇ ⢸  ⠿      ⠿  ⠇ ⢸⢸⣿⢸⢸",
      "⠘⠣⢿⠰⠠⡀     ⢤⣀⣀⡤     ⢀⢄⠆⡿⠜ ",
      "   ⠢⡑⢌⡒⠠⠤⢀⣀⣀⣀⣀⣀⣀⡀⠤⠄⢒⡡⢂⠔   ",
      "     ⠁⠂⠭⠅⣐⣒⣀⣀⣀⣐⣒⣂⠨⠭⠒⠈     ",
    ],
    blink: [
      "       ⠄⠒⠉⠉⢈⣉⡉⠉⠉⠉⠒⠠       ",
      "    ⢠⠌     ⠈⠆⠱⣠⡰⡒  ⠈⠠⡄    ",
      "   ⠠⠁     ⢀⣠⢥⣲⠙⡉     ⠈⠄   ",
      "  ⢀⠂⢀⠤⠤⢄⣀ ⠈⠉⠁ ⠢⠕ ⣀⠠⠤⠤⡀⠐⡀  ",
      "⢠⡔⣾⠰⠡⠊⠉⠁⠒⠪⠭⢒⣒⣒⡒⠭⠕⠒⠈⠉⠑⠌⠆⣿⢢⡄",
      "⡅⡇⣿⠅⡇                ⢸⠨⣿⢸⢨",
      "⡇⡇⣿⡇⡇ ⠐⠒⠒⠒      ⠐⠒⠒⠂ ⢸⢸⣿⢸⢸",
      "⠘⠣⢿⠰⠠⡀     ⢤⣀⣀⡤     ⢀⢄⠆⡿⠜ ",
      "   ⠢⡑⢌⡒⠠⠤⢀⣀⣀⣀⣀⣀⣀⡀⠤⠄⢒⡡⢂⠔   ",
      "     ⠁⠂⠭⠅⣐⣒⣀⣀⣀⣐⣒⣂⠨⠭⠒⠈     ",
    ],
    mask: [
      "       wwwwwwwwwwww       ",
      "    ww     xxxxxx  www    ",
      "   ww     xxxxxx     ww   ",
      "  wwwwwww xxx xx wwwwwww  ",
      "wwwwwwwwwwwwwwwwwwwwwwwwww",
      "wwwww bbbb      bbbb wwwww",
      "wwwww b  b      b  b wwwww",
      "wwwwww     bbbb     wwwww ",
      "   wwwwwwwwwwwwwwwwwwww   ",
      "     wwwwwwwwwwwwwwww     ",
    ],
    blinkMask: [
      "       wwwwwwwwwwww       ",
      "    ww     xxxxxx  www    ",
      "   ww     xxxxxx     ww   ",
      "  wwwwwww xxx xx wwwwwww  ",
      "wwwwwwwwwwwwwwwwwwwwwwwwww",
      "wwwww                wwwww",
      "wwwww bbbb      bbbb wwwww",
      "wwwwww     bbbb     wwwww ",
      "   wwwwwwwwwwwwwwwwwwww   ",
      "     wwwwwwwwwwwwwwww     ",
    ],
  },
];
